name: Update counter JSON

on:
  workflow_dispatch:
  schedule:
    - cron: '*/2 * * * *' # cada 2 minutos

permissions:
  contents: write

jobs:
  fetch-counter:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: npm run build

      - name: Fetch counter from API
        env:
          API_KEY: ${{ secrets.COUNTER_API_KEY }}
        run: |
          echo "Fetching counter..."
          mkdir -p public
          curl -s -H "Authorization: Bearer $API_KEY" \
            https://api.counterapi.dev/v2/daniel-garcias-team-4475/first-counter-4475 \
            -o public/counter.json
          echo "Saved to public/counter.json"
          cp public/counter.json dist/counter.json

      - name: Deploy dist to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
